import type { Topic, TopicId } from './types'

export const CURRICULUM_SOURCES = {
  weights: 'https://www.cfainstitute.org/programs/cfa-program/candidate-resources/level-i-exam',
  modules: 'https://www.cfainstitute.org/sites/default/files/docs/programs/cfa-program/2026-l1-topics-combined.pdf',
} as const

export const TOPICS: Topic[] = [
  {
    id: 'ethics',
    code: 'ETH',
    name: 'Ethical and Professional Standards',
    shortName: 'Ethics',
    session: 1,
    weightMin: 15,
    weightMax: 20,
    hard: false,
    bankTarget: 210,
    summary: 'Professionalism, the Code and Standards, and the purpose of fair performance presentation under the GIPS standards.',
    los: [
      { id: 'eth-trust', title: 'Ethics and Trust in the Investment Profession', summary: 'What a profession owes clients, and a practical way to think through an ethical decision.' },
      { id: 'eth-code', title: 'Code of Ethics and Standards of Professional Conduct', summary: 'How the Code is organized, how the Professional Conduct Program works, and what the seven Standards cover.' },
      { id: 'eth-guidance', title: 'Guidance for Standards I–VII', summary: 'Apply the Standards to original fact patterns and tell a violation from compliant conduct.' },
      { id: 'eth-gips', title: 'Introduction to the Global Investment Performance Standards (GIPS)', summary: 'Why comparable performance reporting exists, and what a firm may claim.' },
      { id: 'eth-application', title: 'Ethics Application', summary: 'Mixed situations that ask which action is the most appropriate next step.' },
    ],
  },
  {
    id: 'quant',
    code: 'QM',
    name: 'Quantitative Methods',
    shortName: 'Quant',
    session: 1,
    weightMin: 6,
    weightMax: 9,
    hard: true,
    bankTarget: 100,
    summary: 'Return math, probability, sampling, and the regression tools used to describe investments.',
    help: {
      blurb: 'Most quant misses come from using the wrong return or the wrong denominator. Name the cash flows, then pick holding-period, time-weighted, or money-weighted on purpose.',
      youtubeUrl: 'https://www.youtube.com/watch?v=QIl6JH_PuW8',
      youtubeTitle: 'Rates and Returns (2025 CFA® Level I Exam – Quantitative Methods – Module 1)',
      channel: 'AnalystPrep',
    },
    los: [
      { id: 'qm-rates', title: 'Rates and Returns', summary: 'Build a required return, then measure holding-period, linked, and money-weighted performance.' },
      { id: 'qm-tvm', title: 'Time Value of Money in Finance', summary: 'Discount bond and equity cash flows, and keep forward rates consistent with spot rates.' },
      { id: 'qm-stats', title: 'Statistical Measures of Asset Returns', summary: 'Location, spread, shape, and correlation for return distributions.' },
      { id: 'qm-probability', title: 'Probability Trees and Conditional Expectations', summary: 'Expected value, trees, and Bayes updates in an investment setting.' },
      { id: 'qm-portmath', title: 'Portfolio Mathematics', summary: 'Portfolio mean and variance, covariance, and Roy’s safety-first ratio.' },
      { id: 'qm-simulation', title: 'Simulation Methods', summary: 'Why prices are often modeled as lognormal, and how Monte Carlo differs from bootstrap.' },
      { id: 'qm-estimation', title: 'Estimation and Inference', summary: 'Sampling choices, the central limit theorem, and the standard error of the mean.' },
      { id: 'qm-hypothesis', title: 'Hypothesis Testing', summary: 'Nulls, p-values, Type I and Type II errors, and parametric versus nonparametric tests.' },
      { id: 'qm-independence', title: 'Parametric and Non-Parametric Tests of Independence', summary: 'Tests that a correlation is zero, and tests on a contingency table.' },
      { id: 'qm-regression', title: 'Simple Linear Regression', summary: 'Least squares, fit, residual warnings, and a prediction from a straight line.' },
      { id: 'qm-bigdata', title: 'Introduction to Big Data Techniques', summary: 'Fintech data, supervised versus unsupervised learning, and overfitting.' },
    ],
  },
  {
    id: 'economics',
    code: 'ECO',
    name: 'Economics',
    shortName: 'Economics',
    session: 1,
    weightMin: 6,
    weightMax: 9,
    hard: false,
    bankTarget: 85,
    summary: 'Market structure, cycles, policy, trade, and exchange-rate arithmetic.',
    los: [
      { id: 'eco-structures', title: 'The Firm and Market Structures', summary: 'Competition types, breakeven, shutdown, and concentration measures.' },
      { id: 'eco-cycles', title: 'Understanding Business Cycles', summary: 'Cycle phases, credit cycles, and the indicators that track them.' },
      { id: 'eco-fiscal', title: 'Fiscal Policy', summary: 'Spending, taxes, deficits, and why implementation is slow.' },
      { id: 'eco-monetary', title: 'Monetary Policy', summary: 'Central-bank tools, targets, and the transmission to rates and the currency.' },
      { id: 'eco-geopolitics', title: 'Introduction to Geopolitics', summary: 'Cooperation versus competition, and how geopolitical tools reach portfolios.' },
      { id: 'eco-trade', title: 'International Trade', summary: 'Gains from trade, tariffs and quotas, and trading blocs.' },
      { id: 'eco-fx', title: 'Capital Flows and the FX Market', summary: 'Who trades currencies, regimes, and why governments restrict capital.' },
      { id: 'eco-fxcalc', title: 'Exchange Rate Calculations', summary: 'Cross-rates, percentage changes, and covered-interest forward rates.' },
    ],
  },
  {
    id: 'fsa',
    code: 'FSA',
    name: 'Financial Statement Analysis',
    shortName: 'FSA',
    session: 1,
    weightMin: 11,
    weightMax: 14,
    hard: true,
    bankTarget: 150,
    summary: 'How the three statements are built, adjusted, and turned into ratios and forecasts.',
    help: {
      blurb: 'Read the ratio as a sentence: which statement is on top, which is on the bottom, and whether the denominator is a flow or a stock. DuPont is that sentence multiplied out.',
      youtubeUrl: 'https://www.youtube.com/watch?v=g2wEFJ7upNs',
      youtubeTitle: 'Financial Analysis Techniques (2025 Level I CFA® Exam – FRA – L.M 11)',
      channel: 'AnalystPrep',
    },
    los: [
      { id: 'fsa-intro', title: 'Introduction to Financial Statement Analysis', summary: 'The analysis framework, filings, notes, and audit opinions.' },
      { id: 'fsa-income', title: 'Analyzing Income Statements', summary: 'Revenue and expense recognition, non-recurring items, and EPS.' },
      { id: 'fsa-balance', title: 'Analyzing Balance Sheets', summary: 'Intangibles, goodwill, financial instruments, and common-size balance sheets.' },
      { id: 'fsa-cf1', title: 'Analyzing Statements of Cash Flows I', summary: 'How the cash flow statement links to the other statements, and IFRS versus US GAAP classification.' },
      { id: 'fsa-cf2', title: 'Analyzing Statements of Cash Flows II', summary: 'Free cash flow and coverage ratios built from the cash flow statement.' },
      { id: 'fsa-inventory', title: 'Analysis of Inventories', summary: 'FIFO, LIFO, weighted average, and the lower of cost and net realizable value.' },
      { id: 'fsa-ltassets', title: 'Analysis of Long-Term Assets', summary: 'Capitalizing, depreciating, impairing, and derecognizing long-lived assets.' },
      { id: 'fsa-liabilities', title: 'Topics in Long-Term Liabilities and Equity', summary: 'Leases, pensions, and share-based pay at a Level I depth.' },
      { id: 'fsa-tax', title: 'Analysis of Income Taxes', summary: 'Tax expense versus taxes paid, and what creates a deferred tax balance.' },
      { id: 'fsa-quality', title: 'Financial Reporting Quality', summary: 'Aggressive versus conservative choices, and warning signs in the statements.' },
      { id: 'fsa-ratios', title: 'Financial Analysis Techniques', summary: 'Activity, liquidity, solvency, profitability, and DuPont.' },
      { id: 'fsa-model', title: 'Introduction to Financial Statement Modeling', summary: 'Sales-driven forecasts, competitive forces, and analyst bias.' },
    ],
  },
  {
    id: 'corporate',
    code: 'CI',
    name: 'Corporate Issuers',
    shortName: 'Corporate',
    session: 1,
    weightMin: 6,
    weightMax: 9,
    hard: false,
    bankTarget: 80,
    summary: 'Governance, working capital, capital allocation, and how a firm is financed.',
    los: [
      { id: 'ci-org', title: 'Organizational Forms, Corporate Issuer Features, and Ownership', summary: 'Sole proprietors through corporations, and public versus private ownership.' },
      { id: 'ci-stakeholders', title: 'Investors and Other Stakeholders', summary: 'Lenders, owners, and the ESG issues investors actually underwrite.' },
      { id: 'ci-governance', title: 'Corporate Governance: Conflicts, Mechanisms, Risks, and Benefits', summary: 'Principal-agent conflicts and the mechanisms that contain them.' },
      { id: 'ci-wc', title: 'Working Capital and Liquidity', summary: 'The cash conversion cycle and liquidity tradeoffs.' },
      { id: 'ci-capalloc', title: 'Capital Investments and Capital Allocation', summary: 'NPV, IRR, ROIC, pitfalls, and real options.' },
      { id: 'ci-structure', title: 'Capital Structure', summary: 'WACC and the Modigliani-Miller claims, with and without taxes.' },
      { id: 'ci-models', title: 'Business Models', summary: 'How a firm gets paid: subscriptions, marketplaces, franchises, and similar designs.' },
    ],
  },
  {
    id: 'equity',
    code: 'EQ',
    name: 'Equity Investments',
    shortName: 'Equity',
    session: 2,
    weightMin: 11,
    weightMax: 14,
    hard: false,
    bankTarget: 145,
    summary: 'Market structure, indexes, efficiency, company analysis, and basic valuation.',
    los: [
      { id: 'eq-markets', title: 'Market Organization and Structure', summary: 'Intermediaries, orders, margin, and primary versus secondary markets.' },
      { id: 'eq-indexes', title: 'Security Market Indexes', summary: 'Price versus total return, and price, value, and equal weighting.' },
      { id: 'eq-efficiency', title: 'Market Efficiency', summary: 'Weak, semi-strong, and strong forms, and what each implies for analysis.' },
      { id: 'eq-overview', title: 'Overview of Equity Securities', summary: 'Common, preferred, voting rights, and market value versus book value.' },
      { id: 'eq-past', title: 'Company Analysis: Past and Present', summary: 'Business model, revenue drivers, margins, and capital structure as they stand today.' },
      { id: 'eq-industry', title: 'Industry and Competitive Analysis', summary: 'Classification, Porter’s five forces, and PESTLE.' },
      { id: 'eq-forecast', title: 'Company Analysis: Forecasting', summary: 'How analysts project revenue, costs, capital spending, and scenarios.' },
      { id: 'eq-valuation', title: 'Equity Valuation: Concepts and Basic Tools', summary: 'Dividend discount models, multiples, and when a price is rich or cheap versus a value estimate.' },
    ],
  },
  {
    id: 'fixed-income',
    code: 'FI',
    name: 'Fixed Income',
    shortName: 'Fixed income',
    session: 2,
    weightMin: 11,
    weightMax: 14,
    hard: true,
    bankTarget: 155,
    summary: 'Bond cash flows, yields, curve math, interest-rate risk, credit, and securitization.',
    help: {
      blurb: 'Duration is a straight-line estimate of an option-free bond’s price change. Add half the convexity times the yield change squared when the curve bends. If the bond has an embedded option, use effective duration instead, because the cash flows can change.',
      youtubeUrl: 'https://www.youtube.com/watch?v=odqDOu46XXI',
      youtubeTitle: 'Yield Based Bond Duration Measures - Module 11 – Fixed Income – CFA® Level I 2026',
      channel: 'FinQuiz Pro',
    },
    los: [
      { id: 'fi-features', title: 'Fixed-Income Instrument Features', summary: 'Indentures, coupons, and affirmative versus negative covenants.' },
      { id: 'fi-cashflows', title: 'Fixed-Income Cash Flows and Types', summary: 'Bullet, amortizing, floating, and contingency provisions.' },
      { id: 'fi-issuance', title: 'Fixed-Income Issuance and Trading', summary: 'How bonds are issued and how the secondary market differs from equities.' },
      { id: 'fi-corpmarkets', title: 'Fixed-Income Markets for Corporate Issuers', summary: 'Commercial paper, repos, and investment-grade versus high-yield funding.' },
      { id: 'fi-govmarkets', title: 'Fixed-Income Markets for Government Issuers', summary: 'Sovereign, non-sovereign, and supranational funding.' },
      { id: 'fi-price', title: 'Fixed-Income Bond Valuation: Prices and Yields', summary: 'Discount the promised cash flows, and read premium versus discount.' },
      { id: 'fi-yields', title: 'Yield and Yield Spread Measures for Fixed-Rate Bonds', summary: 'Current yield, yield to maturity, periodicity, and benchmark spreads.' },
      { id: 'fi-floaters', title: 'Yield and Yield Spread Measures for Floating-Rate Instruments', summary: 'Quoted margin, discount margin, and money-market yields.' },
      { id: 'fi-curve', title: 'The Term Structure of Interest Rates: Spot, Par, and Forward Curves', summary: 'Bootstrapping spots and the forwards implied by them.' },
      { id: 'fi-return', title: 'Interest Rate Risk and Return', summary: 'Coupon, reinvestment, and price change as the three sources of bond return.' },
      { id: 'fi-duration', title: 'Yield-Based Bond Duration Measures and Properties', summary: 'Macaulay, modified, money duration, and the price value of a basis point.' },
      { id: 'fi-convexity', title: 'Yield-Based Bond Convexity and Portfolio Properties', summary: 'The convexity adjustment and portfolio-level duration.' },
      { id: 'fi-curve-risk', title: 'Curve-Based and Empirical Fixed-Income Risk Measures', summary: 'Effective duration, key-rate duration, and empirical versus analytical duration.' },
      { id: 'fi-credit', title: 'Credit Risk', summary: 'Default probability, loss given default, and what ratings do and do not say.' },
      { id: 'fi-credit-gov', title: 'Credit Analysis for Government Issuers', summary: 'Ability and willingness to pay, in local currency and in foreign currency.' },
      { id: 'fi-credit-corp', title: 'Credit Analysis for Corporate Issuers', summary: 'Coverage, leverage, seniority, and recovery.' },
      { id: 'fi-securitization', title: 'Fixed-Income Securitization', summary: 'Why pools of loans are tranched, and who does which job.' },
      { id: 'fi-abs', title: 'Asset-Backed Security (ABS) Instrument and Market Features', summary: 'Credit enhancement, covered bonds, and non-mortgage ABS.' },
      { id: 'fi-mbs', title: 'Mortgage-Backed Security (MBS) Instrument and Market Features', summary: 'Prepayment, pass-throughs, CMOs, and commercial mortgage deals.' },
    ],
  },
  {
    id: 'derivatives',
    code: 'DER',
    name: 'Derivatives',
    shortName: 'Derivatives',
    session: 2,
    weightMin: 5,
    weightMax: 8,
    hard: true,
    bankTarget: 80,
    summary: 'Forwards, futures, swaps, and options: payoffs, pricing, and replication.',
    help: {
      blurb: 'Separate price from value. A forward is priced so its value starts at zero; value appears later as the spot moves. A swap is a package of those forwards. An option adds the right to walk away, so put-call parity is the no-arbitrage link among the call, the put, the underlying, and a risk-free bond.',
      youtubeUrl: 'https://www.youtube.com/watch?v=I5xvmxZqb10',
      youtubeTitle: 'Pricing and Valuation of Swaps - Module 7 – Derivatives – CFA® Level I 2026',
      channel: 'FinQuiz Pro',
    },
    los: [
      { id: 'der-features', title: 'Derivative Instrument and Derivative Market Features', summary: 'What makes a derivative, and how exchange-traded markets differ from OTC.' },
      { id: 'der-instruments', title: 'Forward Commitment and Contingent Claim Features and Instruments', summary: 'Forwards, futures, swaps, calls, puts, and credit derivatives.' },
      { id: 'der-uses', title: 'Derivative Benefits, Risks, and Issuer and Investor Uses', summary: 'Why issuers and investors use these contracts, and how the risks show up.' },
      { id: 'der-carry', title: 'Arbitrage, Replication, and the Cost of Carry in Pricing Derivatives', summary: 'Replication, the law of one price, and net cost of carry.' },
      { id: 'der-forwards', title: 'Pricing and Valuation of Forward Contracts', summary: 'Forward price at initiation and value before expiration.' },
      { id: 'der-futures', title: 'Pricing and Valuation of Futures Contracts', summary: 'Why futures and forward prices can differ when rates and prices move together.' },
      { id: 'der-swaps', title: 'Pricing and Valuation of Interest Rates and Other Swaps', summary: 'A swap as a series of forwards, and the net payment on a settlement date.' },
      { id: 'der-options', title: 'Pricing and Valuation of Options', summary: 'Moneyness, exercise value, time value, and the option Greeks at a Level I depth.' },
      { id: 'der-parity', title: 'Option Replication Using Put–Call Parity', summary: 'European put-call parity and the forward version of the same relation.' },
      { id: 'der-binomial', title: 'Valuing a Derivative Using a One-Period Binomial Model', summary: 'The hedge ratio and the risk-neutral probability in a one-step tree.' },
    ],
  },
  {
    id: 'alternatives',
    code: 'AI',
    name: 'Alternative Investments',
    shortName: 'Alternatives',
    session: 2,
    weightMin: 7,
    weightMax: 10,
    hard: false,
    bankTarget: 100,
    summary: 'Private capital, real assets, hedge funds, and digital assets, including fees.',
    los: [
      { id: 'ai-features', title: 'Alternative Investment Features, Methods, and Structures', summary: 'Direct, co-invest, and fund access, plus typical fee structures.' },
      { id: 'ai-returns', title: 'Alternative Investment Performance and Returns', summary: 'Fee math, high-water marks, and multiples of invested capital.' },
      { id: 'ai-private', title: 'Investments in Private Capital: Equity and Debt', summary: 'Buyout, venture, and private-debt characteristics, including the J-curve.' },
      { id: 'ai-real', title: 'Real Estate and Infrastructure', summary: 'Cap rates, REITs, and availability versus demand risk in infrastructure.' },
      { id: 'ai-natural', title: 'Natural Resources', summary: 'Timber, farmland, and the three pieces of a commodity return.' },
      { id: 'ai-hedge', title: 'Hedge Funds', summary: 'Strategy families, biases in hedge-fund indexes, and liquidity terms.' },
      { id: 'ai-digital', title: 'Introduction to Digital Assets', summary: 'Distributed ledgers, tokens, and the risks that do not diversify away in stress.' },
    ],
  },
  {
    id: 'portfolio',
    code: 'PM',
    name: 'Portfolio Management',
    shortName: 'Portfolio',
    session: 2,
    weightMin: 8,
    weightMax: 12,
    hard: true,
    bankTarget: 115,
    summary: 'Risk and return, the CAPM, the IPS, behavioral biases, and risk management.',
    help: {
      blurb: 'Portfolio variance is not the average of the variances unless the assets move together perfectly. Correlation below one is the diversification. CAPM then prices only the risk you cannot diversify: expected return equals the risk-free rate plus beta times the market risk premium.',
      youtubeUrl: 'https://www.youtube.com/watch?v=DLKhsZvcD-c',
      youtubeTitle: 'Portfolio Risk and Return - Part I (2025 Level I CFA® Exam – PM – Module 1)',
      channel: 'AnalystPrep',
    },
    los: [
      { id: 'pm-part1', title: 'Portfolio Risk and Return: Part I', summary: 'Utility, the efficient frontier, and two-asset risk.' },
      { id: 'pm-part2', title: 'Portfolio Risk and Return: Part II', summary: 'The capital market line, beta, the CAPM, and risk-adjusted performance.' },
      { id: 'pm-overview', title: 'Portfolio Management: An Overview', summary: 'The portfolio approach, client types, and pooled products.' },
      { id: 'pm-ips', title: 'Basics of Portfolio Planning and Construction', summary: 'The investment policy statement, risk capacity versus willingness, and constraints.' },
      { id: 'pm-behavior', title: 'The Behavioral Biases of Individuals', summary: 'Cognitive errors, emotional biases, and the portfolio damage they cause.' },
      { id: 'pm-risk', title: 'Introduction to Risk Management', summary: 'Governance, risk budgeting, and how exposures are modified.' },
    ],
  },
]

const byId = new Map(TOPICS.map((topic) => [topic.id, topic]))

export function getTopic(id: TopicId): Topic {
  const topic = byId.get(id)
  if (!topic) throw new Error(`Unknown topic ${id}`)
  return topic
}

export function allLosIds(): string[] {
  return TOPICS.flatMap((topic) => topic.los.map((los) => los.id))
}

export const BANK_TARGET_TOTAL = TOPICS.reduce((sum, topic) => sum + topic.bankTarget, 0)
